"""Postgres: schema + migrations + the RLS policies with a per-user cap, using a bundled local Postgres and a stubbed auth.uid()."""
import os, sys, tempfile
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import pgserver
pg = pgserver.get_server(tempfile.mkdtemp())
url = pg.get_uri()
os.environ["DATABASE_URL"] = url; os.environ["MAX_ITEMS_PER_USER"] = "3"
import pricewatch
from pricewatch import db, config
db.DATABASE_URL = url; config.MAX_ITEMS_PER_USER = 3
fails = []
def check(c, m): print(("ok   " if c else "FAIL ") + m); c or fails.append(m)
import psycopg
root = psycopg.connect(url, autocommit=True)
root.execute("""CREATE SCHEMA IF NOT EXISTS auth;
  CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
  DO $$ BEGIN CREATE ROLE anon NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;
  DO $$ BEGIN CREATE ROLE authenticated NOLOGIN; EXCEPTION WHEN duplicate_object THEN NULL; END $$;""")
# old-style schema first (no new columns), then connect() must migrate
root.execute("""CREATE TABLE items (id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, user_id UUID, url TEXT NOT NULL, store TEXT, name TEXT, image_url TEXT,
  size TEXT, target_price REAL, currency TEXT, active INTEGER NOT NULL DEFAULT 1, notify_restock INTEGER NOT NULL DEFAULT 0, fail_count INTEGER NOT NULL DEFAULT 0,
  last_error TEXT, created_at TEXT NOT NULL);
  CREATE TABLE profiles (user_id UUID PRIMARY KEY, email TEXT, telegram_chat_id TEXT, created_at TEXT);""")
conn = db.connect()
cols = {r[0] for r in root.execute("SELECT column_name FROM information_schema.columns WHERE table_name='items'").fetchall()}
check({"check_requested", "sizes_json"} <= cols, "postgres migration adds new columns")
import setup_supabase
conn.executescript(setup_supabase.SQL); conn.close()
pols = {r[0] for r in root.execute("SELECT policyname FROM pg_policies WHERE tablename='items'").fetchall()}
check(pols == {"items_select", "items_insert", "items_update", "items_delete"}, f"items policies split: {sorted(pols)}")

U1, U2 = "11111111-1111-1111-1111-111111111111", "22222222-2222-2222-2222-222222222222"
def as_user(uid):
    c = psycopg.connect(url, autocommit=True); c.execute("SET ROLE authenticated"); c.execute(f"SET request.jwt.claim.sub = '{uid}'"); return c
u1, u2 = as_user(U1), as_user(U2)
for i in range(3):
    u1.execute("INSERT INTO items (url, created_at, check_requested) VALUES (%s, now()::text, 1)", (f"https://x/{i}",))
try:
    u1.execute("INSERT INTO items (url, created_at) VALUES ('https://x/4', now()::text)"); check(False, "4th item should be rejected")
except psycopg.errors.InsufficientPrivilege as e:
    check("row-level security" in str(e), "cap: 4th item rejected by RLS")
u2.execute("INSERT INTO items (url, created_at) VALUES ('https://y/1', now()::text)")
check(u2.execute("SELECT count(*) FROM items").fetchone()[0] == 1, "user 2 sees only their own item")
check(u1.execute("SELECT count(*) FROM items").fetchone()[0] == 3, "user 1 sees only their 3")
check(u2.execute("SELECT user_id FROM items").fetchone()[0] == __import__("uuid").UUID(U2), "user_id defaulted to auth.uid()")
u1.execute("UPDATE items SET check_requested = 1, size = 'M' WHERE url = 'https://x/0'")
check(u1.execute("SELECT check_requested FROM items WHERE url='https://x/0'").fetchone()[0] == 1, "user can set check_requested")
try:
    u1.execute("UPDATE items SET user_id = %s WHERE url = 'https://x/0'", (U2,)); check(False, "should not be able to give an item away")
except psycopg.errors.InsufficientPrivilege:
    check(True, "cannot reassign an item to another user")
# cron (owner) writes history; user can read only their own; delete cascades
root.execute("INSERT INTO price_history (item_id, price, in_stock, checked_at) SELECT id, 10, 1, now()::text FROM items")
check(u1.execute("SELECT count(*) FROM price_history").fetchone()[0] == 3, "history visible only for own items")
u1.execute("DELETE FROM items WHERE url = 'https://x/0'")
check(root.execute("SELECT count(*) FROM price_history").fetchone()[0] == 3, "delete cascades history (4 -> 3)")
check(u1.execute("SELECT public.my_item_count()").fetchone()[0] == 2, "my_item_count works for the user")
u1.execute("INSERT INTO items (url, created_at) VALUES ('https://x/5', now()::text)"); check(True, "after a delete, can add again")
# profiles: delete own, cannot see others
u1.execute("INSERT INTO profiles (user_id, email) VALUES (%s, 'a@b')", (U1,)); u2.execute("INSERT INTO profiles (user_id, email) VALUES (%s, 'c@d')", (U2,))
check(u1.execute("SELECT count(*) FROM profiles").fetchone()[0] == 1, "profiles isolated")
u1.execute("DELETE FROM profiles WHERE user_id = %s", (U1,)); check(root.execute("SELECT count(*) FROM profiles").fetchone()[0] == 1, "user can delete own profile")
# due_items on postgres with the new ordering
conn = db.connect()
due = db.due_items(conn, 6); conn.close()
check([r["check_requested"] for r in due][0] == 1 and len(due) == 4, f"due_items runs on postgres, requested first ({len(due)} due)")
u1.close(); u2.close(); root.close(); pg.cleanup()
print(f"\n{len(fails)} failure(s)"); sys.exit(1 if fails else 0)
